Clazz.declarePackage ("astex.map");
c$ = Clazz.decorateAsClass (function () {
this.map = null;
this.x = 0;
this.y = 0;
this.z = 0;
this.alpha = 0;
this.beta = 0;
this.gamma = 0;
this.level = 0;
this.scale = 0;
this.size = 0;
this.iGridVal = null;
this.iGridMin = null;
this.iGridMax = null;
this.showMap = false;
this.showGrid = false;
this.invert = false;
this.cutSelection = false;
this.cutDistance = 0;
this.iStyle = 0;
this.color = 0;
this.transparency = 0;
this.showMaskLabel = false;
this.nMasks = 0;
this.centerMap = false;
Clazz.instantialize (this, arguments);
}, astex.map, "MapState");
Clazz.prepareFields (c$, function () {
this.iGridVal =  Clazz.newIntArray (3, 0);
this.iGridMin =  Clazz.newIntArray (3, 0);
this.iGridMax =  Clazz.newIntArray (3, 0);
});
